name: oes_chatbot
description: A new Flutter package project.
version: 0.0.1-dev.1
homepage: test

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.4
  dartz: ^0.10.1

  flutter:
    sdk: flutter
  get_it: ^7.6.4
  native_flutter_proxy: ^0.1.15
  equatable: ^2.0.5
  encrypt: ^5.0.3
  flutter_bloc: ^8.1.3
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.46
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  emoji_picker_flutter: ^1.6.3
  flutter_spinkit: ^5.2.0
  intl: ^0.18.0
  syncfusion_flutter_core:
  video_player: ^2.6.1
  visibility_detector: ^0.4.0+2
  shimmer: ^3.0.0
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  lottie: ^2.3.2
  http: ^1.1.0
  path: ^1.8.3
  mime: ^1.0.4
  http_parser: ^4.0.2
  image_cropper: ^5.0.1
  another_flushbar: ^1.12.30
  printing: ^5.11.1
  path_provider: ^2.1.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/chat_bot_assets/
    - assets/ticketStatus/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
